### ISSUE TITLE
Reexport <$!>

### ISSUE THREAD

**Issue by andrewthad** [chessai/constrictor#1]
I just rediscovered the real problem with reimplementing `<$!>`. If a user imports `Control.Monad` and `Control.Monad.Constrictor`, they currently get an error when they try to use `<$!>`, since GHC doesn't know which one to pick. If you reexport the one from `Control.Monad` instead of rolling your own, this problem doesn't happen. It's annoying that you don't get to write your own docs, but you can mitigate this somewhat by following the [convention that Gabriel uses in `pipes`](http://hackage.haskell.org/package/pipes-4.3.9/docs/Pipes.html#g:7), having a reexports section in your haddocks. You aren't doing a whole-module reexport, but this would at least help put the docs from `base` (with the `since` annotation) in context for the user.

**Comment by chessai** [comment]
We discussed this the other day IRL and I think I decided that I just want users to import Control.Monad hiding ((<$!>)), or import Constrictor hiding ((<$!>)). If you think of another reason that I should do what Gabriel does in pipes, you can reopen this issue.
